name: tw2
forward_potential:
  kind: denseicnn
  hidden_dims: [128, 128, 64]
  rank: 1
  activation: celu
  dropout: 0.0
  strong_convexity: 1.0e-4
  identity_quadratic: 0.0
  weights_init_std: 0.1
inverse_potential:
  kind: denseicnn
  hidden_dims: [128, 128, 64]
  rank: 1
  activation: celu
  dropout: 0.0
  strong_convexity: 1.0e-4
  identity_quadratic: 0.0
  weights_init_std: 0.1
lr: 1.0e-3
cycle_weight: 64.0
identity_pretrain_steps: 5000
identity_pretrain_batch_size: 1024
identity_pretrain_lr: 1.0e-3
identity_pretrain_blow: 3.0
identity_pretrain_tol: 1.0e-3
compile: false
